Repository PortAudio/portaudio, pull requests merged in 2023-04, with the labels that each got.

#783 improvements to paqa_devs.c
  qa/paqa_devs.c
  qa/paqa_errs.c
  qa/paqa_macros.h
Labels: test-qa

#794 Pa_Initialize(): Guard against recursive calls.
  include/portaudio.h
  src/common/pa_front.c
Labels: src-common, final merge review

#806 docs: warn against using PaUtil_GetTime when a specific clock is required.
  src/common/pa_util.h
Labels: documentation, final merge review

#780 Treat warnings as errors on CI
  .github/workflows/cmake.yml
  CMakeLists.txt
Labels: CI

#812 Remove some warnings from allowlist
  CMakeLists.txt
Labels: final merge review

#721 Add cmake files for cpp bindings
  .gitignore
  bindings/cpp/CMakeLists.txt
  bindings/cpp/cmake/PortAudioCppConfig.cmake.in
  bindings/cpp/cmake/modules/FindASIO.cmake
  bindings/cpp/cmake/modules/FindPortAudio.cmake
  bindings/cpp/cmake/portaudiocpp.pc.in
  bindings/cpp/source/portaudiocpp/CMakeLists.txt
Labels: build-cmake
